# Generated by Django 4.1.7 on 2023-02-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="date",
        ),
        migrations.AlterField(
            model_name="pod",
            name="rss_link",
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="cover_image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
