# Generated by Django 4.1.7 on 2023-02-18 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0002_remove_podcast_date_alter_pod_rss_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pod",
            name="podcast",
        ),
        migrations.AddField(
            model_name="podcast",
            name="rss",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="podcasts.pod",
            ),
        ),
    ]
